// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuqewifjjywkltxlrolw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cWV3aWZqanl3a2x0eGxyb2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTM3MDgsImV4cCI6MjA1NzYyOTcwOH0.NnoOswJtynCm8044Q5ENtLPkmXOUIvfdtjcfKCCrpxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);